apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: milvus-rag-web-app
spec:
  template:
    spec:
      containers:
        - name: main-app
          image: us-central1-docker.pkg.dev/milvus-rag-web-app/milvus-rag-web-app/main-app:latest
          ports:
            - containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 60
        - name: query-embedding-model
          image: us-central1-docker.pkg.dev/milvus-rag-web-app/milvus-rag-web-app/query-embedding-model:latest
          env:
            - name: PORT
              value: "5000"
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
            limits:
              cpu: "2"
              memory: 8Gi
          startupProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 60
        - name: ollama-gemma
          image: us-central1-docker.pkg.dev/milvus-rag-web-app/milvus-rag-web-app/ollama-gemma:latest
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
            limits:
              cpu: "2"
              memory: 8Gi
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 60
    metadata:
      annotations:
         run.googleapis.com/container-dependencies: '{"main-app":["query-embedding-model","ollama-gemma"]}'
