# Container services for the app, gemma, and query embedding model
services:

  milvus-rag-web-app:
    build:
      context: .
      dockerfile: milvus-rag-web-app.dockerfile
    image: milvus-rag-web-app
    ports:
      - "8080:8080"
    networks:
      - milvus-rag-network
    depends_on:
      - ollama-gemma
      - query-embedding-model
  
  ollama-gemma:
    build:
      context: .
      dockerfile: ollama-gemma/ollama-gemma.dockerfile
    image: ollama-gemma
    ports:
      - "3000:3000"
    networks:
      - milvus-rag-network
  
  query-embedding-model:
    build:
      context: .
      dockerfile: query-embedding-model/query-embedding-model.dockerfile
    image: query-embedding-model
    ports:
      - "5000:5000"
    networks:
      - milvus-rag-network

# Define the network for the services
networks:
  milvus-rag-network:
    driver: bridge
